-- MySQL Script generated by MySQL Workbench
-- Sat Sep 25 17:28:27 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema nekretnine_database
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `nekretnine_database` ;

-- -----------------------------------------------------
-- Schema nekretnine_database
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `nekretnine_database` DEFAULT CHARACTER SET utf8 ;
USE `nekretnine_database` ;

-- -----------------------------------------------------
-- Table `nekretnine_database`.`Mjesto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Mjesto` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Mjesto` (
  `BrPoste` VARCHAR(5) NOT NULL,
  `Naziv` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`BrPoste`),
  UNIQUE INDEX `BrPoste_UNIQUE` (`BrPoste` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`Osoba`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Osoba` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Osoba` (
  `JMB` VARCHAR(13) NOT NULL,
  `Ime` VARCHAR(45) NOT NULL,
  `Prezime` VARCHAR(45) NOT NULL,
  `BrTelefona` VARCHAR(45) NULL,
  `Pol` TINYINT NOT NULL,
  `BrPoste` VARCHAR(5) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`JMB`),
  UNIQUE INDEX `JMB_UNIQUE` (`JMB` ASC) VISIBLE,
  INDEX `fk_Osoba_Mjesto1_idx` (`BrPoste` ASC) VISIBLE,
  CONSTRAINT `fk_Osoba_Mjesto1`
    FOREIGN KEY (`BrPoste`)
    REFERENCES `nekretnine_database`.`Mjesto` (`BrPoste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`Klijent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Klijent` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Klijent` (
  `JMB` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`JMB`),
  CONSTRAINT `fk_Klijent_Osoba`
    FOREIGN KEY (`JMB`)
    REFERENCES `nekretnine_database`.`Osoba` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`Agencija`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Agencija` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Agencija` (
  `idAgencija` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(45) NOT NULL,
  `BrTelefona` VARCHAR(45) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  `BrPoste` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idAgencija`),
  INDEX `fk_Agencija_Mjesto1_idx` (`BrPoste` ASC) VISIBLE,
  CONSTRAINT `fk_Agencija_Mjesto1`
    FOREIGN KEY (`BrPoste`)
    REFERENCES `nekretnine_database`.`Mjesto` (`BrPoste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`Agent`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Agent` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Agent` (
  `JMB` VARCHAR(13) NOT NULL,
  `Plata` DECIMAL(9,3) NOT NULL,
  `idAgencija` INT NOT NULL,
  PRIMARY KEY (`JMB`),
  INDEX `fk_Agent_Agencija1_idx` (`idAgencija` ASC) VISIBLE,
  CONSTRAINT `fk_Agent_Osoba1`
    FOREIGN KEY (`JMB`)
    REFERENCES `nekretnine_database`.`Osoba` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Agent_Agencija1`
    FOREIGN KEY (`idAgencija`)
    REFERENCES `nekretnine_database`.`Agencija` (`idAgencija`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`Vlasnik`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Vlasnik` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Vlasnik` (
  `JMB` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`JMB`),
  CONSTRAINT `fk_Vlasnik_Osoba1`
    FOREIGN KEY (`JMB`)
    REFERENCES `nekretnine_database`.`Osoba` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`KarakteristikaNekretnine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`KarakteristikaNekretnine` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`KarakteristikaNekretnine` (
  `idKarakteristikaNekretnine` INT NOT NULL AUTO_INCREMENT,
  `Naziv` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`idKarakteristikaNekretnine`),
  UNIQUE INDEX `idKarakteristikaNekretnine_UNIQUE` (`idKarakteristikaNekretnine` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`Klijent_zahtjeva_KarakteristikaNekretnine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Klijent_zahtjeva_KarakteristikaNekretnine` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Klijent_zahtjeva_KarakteristikaNekretnine` (
  `Klijent_JMB` VARCHAR(13) NOT NULL,
  `KarakteristikaNekretnine_idKarakteristikaNekretnine` INT NOT NULL,
  `DodatniOpis` VARCHAR(100) NULL,
  PRIMARY KEY (`Klijent_JMB`, `KarakteristikaNekretnine_idKarakteristikaNekretnine`),
  INDEX `fk_Klijent_has_KarakteristikaNekretnine_KarakteristikaNekre_idx` (`KarakteristikaNekretnine_idKarakteristikaNekretnine` ASC) VISIBLE,
  INDEX `fk_Klijent_has_KarakteristikaNekretnine_Klijent1_idx` (`Klijent_JMB` ASC) VISIBLE,
  CONSTRAINT `fk_Klijent_has_KarakteristikaNekretnine_Klijent1`
    FOREIGN KEY (`Klijent_JMB`)
    REFERENCES `nekretnine_database`.`Klijent` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Klijent_has_KarakteristikaNekretnine_KarakteristikaNekretn1`
    FOREIGN KEY (`KarakteristikaNekretnine_idKarakteristikaNekretnine`)
    REFERENCES `nekretnine_database`.`KarakteristikaNekretnine` (`idKarakteristikaNekretnine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`Nekretnina`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Nekretnina` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Nekretnina` (
  `idNekretnina` INT NOT NULL AUTO_INCREMENT,
  `BrPoste` VARCHAR(5) NOT NULL,
  `Adresa` VARCHAR(45) NOT NULL,
  `Vlasnik_JMB` VARCHAR(13) NOT NULL,
  PRIMARY KEY (`idNekretnina`),
  UNIQUE INDEX `idNekretnina_UNIQUE` (`idNekretnina` ASC) VISIBLE,
  INDEX `fk_Nekretnina_Mjesto1_idx` (`BrPoste` ASC) VISIBLE,
  INDEX `fk_Nekretnina_Vlasnik1_idx` (`Vlasnik_JMB` ASC) VISIBLE,
  CONSTRAINT `fk_Nekretnina_Mjesto1`
    FOREIGN KEY (`BrPoste`)
    REFERENCES `nekretnine_database`.`Mjesto` (`BrPoste`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nekretnina_Vlasnik1`
    FOREIGN KEY (`Vlasnik_JMB`)
    REFERENCES `nekretnine_database`.`Vlasnik` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`Nekretnina_ima_KarakteristikaNekretnine`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Nekretnina_ima_KarakteristikaNekretnine` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Nekretnina_ima_KarakteristikaNekretnine` (
  `Nekretnina_idNekretnina` INT NOT NULL,
  `KarakteristikaNekretnine_idKarakteristikaNekretnine` INT NOT NULL,
  `DodatniOpis` VARCHAR(45) NULL,
  PRIMARY KEY (`Nekretnina_idNekretnina`, `KarakteristikaNekretnine_idKarakteristikaNekretnine`),
  INDEX `fk_Nekretnina_has_KarakteristikaNekretnine_KarakteristikaNe_idx` (`KarakteristikaNekretnine_idKarakteristikaNekretnine` ASC) VISIBLE,
  INDEX `fk_Nekretnina_has_KarakteristikaNekretnine_Nekretnina1_idx` (`Nekretnina_idNekretnina` ASC) VISIBLE,
  CONSTRAINT `fk_Nekretnina_has_KarakteristikaNekretnine_Nekretnina1`
    FOREIGN KEY (`Nekretnina_idNekretnina`)
    REFERENCES `nekretnine_database`.`Nekretnina` (`idNekretnina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Nekretnina_has_KarakteristikaNekretnine_KarakteristikaNekr1`
    FOREIGN KEY (`KarakteristikaNekretnine_idKarakteristikaNekretnine`)
    REFERENCES `nekretnine_database`.`KarakteristikaNekretnine` (`idKarakteristikaNekretnine`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`NekretninaProdaja`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`NekretninaProdaja` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`NekretninaProdaja` (
  `idNekretnina` INT NOT NULL,
  `PredlozenaCijena` DECIMAL(9,3) NOT NULL,
  `jeProdana` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idNekretnina`),
  CONSTRAINT `fk_NekretninaProdaja_Nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `nekretnine_database`.`Nekretnina` (`idNekretnina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`NekretninaIznajmljivanje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`NekretninaIznajmljivanje` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`NekretninaIznajmljivanje` (
  `idNekretnina` INT NOT NULL,
  `PredlozenaKirija` DECIMAL(9,3) NOT NULL,
  `SlobodnoOd` DATE NOT NULL,
  `SlobodnoDo` DATE NULL,
  `jeIznajmljena` TINYINT NULL DEFAULT 0,
  PRIMARY KEY (`idNekretnina`),
  CONSTRAINT `fk_NekretninaIznajmljivanje_Nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `nekretnine_database`.`Nekretnina` (`idNekretnina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`KupoprodajniUgovor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`KupoprodajniUgovor` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`KupoprodajniUgovor` (
  `idKupoprodajniUgovor` INT NOT NULL AUTO_INCREMENT,
  `Klijent_JMB` VARCHAR(13) NOT NULL,
  `Agent_JMB` VARCHAR(13) NOT NULL,
  `Datum` DATE NOT NULL,
  `Cijena` DECIMAL(9,3) NOT NULL,
  `Opis` TEXT(200) NULL,
  `NekretninaProdaja_idNekretnina` INT NOT NULL,
  PRIMARY KEY (`idKupoprodajniUgovor`, `Klijent_JMB`, `Agent_JMB`),
  UNIQUE INDEX `idKupoprodajniUgovor_UNIQUE` (`idKupoprodajniUgovor` ASC) VISIBLE,
  INDEX `fk_KupoprodajniUgovor_Klijent1_idx` (`Klijent_JMB` ASC) VISIBLE,
  INDEX `fk_KupoprodajniUgovor_Agent1_idx` (`Agent_JMB` ASC) VISIBLE,
  INDEX `fk_KupoprodajniUgovor_NekretninaProdaja1_idx` (`NekretninaProdaja_idNekretnina` ASC) VISIBLE,
  CONSTRAINT `fk_KupoprodajniUgovor_Klijent1`
    FOREIGN KEY (`Klijent_JMB`)
    REFERENCES `nekretnine_database`.`Klijent` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KupoprodajniUgovor_Agent1`
    FOREIGN KEY (`Agent_JMB`)
    REFERENCES `nekretnine_database`.`Agent` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_KupoprodajniUgovor_NekretninaProdaja1`
    FOREIGN KEY (`NekretninaProdaja_idNekretnina`)
    REFERENCES `nekretnine_database`.`NekretninaProdaja` (`idNekretnina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`UgovorIznajmljivanje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`UgovorIznajmljivanje` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`UgovorIznajmljivanje` (
  `idUgovorIznajmljivanje` INT NOT NULL AUTO_INCREMENT,
  `Klijent_JMB` VARCHAR(13) NOT NULL,
  `Agent_JMB` VARCHAR(13) NOT NULL,
  `Kirija` DECIMAL(9,3) NOT NULL,
  `Datum` DATE NOT NULL,
  `Opis` TEXT(200) NULL,
  `Depozit` DECIMAL(9,3) NULL,
  `MinimalanPeriodIznajmljivanja` INT NULL,
  `NekretninaIznajmljivanje_idNekretnina` INT NOT NULL,
  PRIMARY KEY (`idUgovorIznajmljivanje`, `Klijent_JMB`, `Agent_JMB`),
  INDEX `fk_UgovorIznajmljivanje_Klijent1_idx` (`Klijent_JMB` ASC) VISIBLE,
  INDEX `fk_UgovorIznajmljivanje_Agent1_idx` (`Agent_JMB` ASC) VISIBLE,
  INDEX `fk_UgovorIznajmljivanje_NekretninaIznajmljivanje1_idx` (`NekretninaIznajmljivanje_idNekretnina` ASC) VISIBLE,
  CONSTRAINT `fk_UgovorIznajmljivanje_Klijent1`
    FOREIGN KEY (`Klijent_JMB`)
    REFERENCES `nekretnine_database`.`Klijent` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UgovorIznajmljivanje_Agent1`
    FOREIGN KEY (`Agent_JMB`)
    REFERENCES `nekretnine_database`.`Agent` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_UgovorIznajmljivanje_NekretninaIznajmljivanje1`
    FOREIGN KEY (`NekretninaIznajmljivanje_idNekretnina`)
    REFERENCES `nekretnine_database`.`NekretninaIznajmljivanje` (`idNekretnina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `nekretnine_database`.`Posjeta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `nekretnine_database`.`Posjeta` ;

CREATE TABLE IF NOT EXISTS `nekretnine_database`.`Posjeta` (
  `idPosjeta` INT NOT NULL AUTO_INCREMENT,
  `Datum` DATE NOT NULL,
  `Klijent_JMB` VARCHAR(13) NOT NULL,
  `Agent_JMB` VARCHAR(13) NOT NULL,
  `idNekretnina` INT NOT NULL,
  PRIMARY KEY (`idPosjeta`, `Klijent_JMB`, `Agent_JMB`, `idNekretnina`),
  UNIQUE INDEX `idPosjeta_UNIQUE` (`idPosjeta` ASC) VISIBLE,
  INDEX `fk_Posjeta_Klijent1_idx` (`Klijent_JMB` ASC) VISIBLE,
  INDEX `fk_Posjeta_Agent1_idx` (`Agent_JMB` ASC) VISIBLE,
  INDEX `fk_Posjeta_Nekretnina1_idx` (`idNekretnina` ASC) VISIBLE,
  CONSTRAINT `fk_Posjeta_Klijent1`
    FOREIGN KEY (`Klijent_JMB`)
    REFERENCES `nekretnine_database`.`Klijent` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posjeta_Agent1`
    FOREIGN KEY (`Agent_JMB`)
    REFERENCES `nekretnine_database`.`Agent` (`JMB`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posjeta_Nekretnina1`
    FOREIGN KEY (`idNekretnina`)
    REFERENCES `nekretnine_database`.`Nekretnina` (`idNekretnina`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

-- TRIGGERS
DELIMITER $$
CREATE TRIGGER azuriraj_stanje_nekretnine_iznajmljivanje
    AFTER INSERT
    ON `UgovorIznajmljivanje` FOR EACH ROW
BEGIN
	    update `NekretninaIznajmljivanje` NI set NI.jeIznajmljena=1 where new.NekretninaIznajmljivanje_idNekretnina=NI.idNekretnina;
END$$    
DELIMITER ;

DELIMITER $$
CREATE TRIGGER azuriraj_stanje_nekretnine_prodaja
    AFTER INSERT
    ON `KupoprodajniUgovor` FOR EACH ROW
BEGIN
	    update `NekretninaProdaja` NP set NP.jeProdana=1 where new.NekretninaProdaja_idNekretnina=NP.idNekretnina;
END$$    
DELIMITER ;

DELIMITER $$
CREATE TRIGGER azuriraj_period_nekretnine_iznajmljivanje
    AFTER INSERT
    ON `UgovorIznajmljivanje` FOR EACH ROW
BEGIN
	    update `NekretninaIznajmljivanje` NI set NI.SlobodnoOd = (NI.SlobodnoOd + INTERVAL new.MinimalanPeriodIznajmljivanja MONTH) where new.NekretninaIznajmljivanje_idNekretnina=NI.idNekretnina;
END$$    
DELIMITER ;

-- VIEWS
create view VIEW_LISTA_NEKRETNINA AS
select N.idNekretnina, N.BrPoste, N.Adresa, N.Vlasnik_JMB, NI.PredlozenaKirija, NI.SlobodnoOd, NI.SlobodnoDo, NI.jeIznajmljena
from nekretnina N 
inner join nekretninaiznajmljivanje NI on NI.idNekretnina=N.idNekretnina;

-- STORED PROCEDURES
DELIMITER $$
CREATE PROCEDURE `SACUVAJ_NEKRETNINU_IZNAJMLJIVANJE_PROCEDURE` (IN IdNekretnina int, IN PredlozenaKirija decimal, IN SlobodnoOd date, IN SlobodnoDo date, IN jeIznajmljena tinyint)
BEGIN
insert into NekretninaIznajmljivanje (idNekretnina,PredlozenaKirija,SlobodnoOd,SlobodnoDo,jeIznajmljena) values (IdNekretnina,PredlozenaKirija,SlobodnoOd,SlobodnoDo,jeIznajmljena);
END$$    
DELIMITER ;

DELIMITER $$
CREATE PROCEDURE `SACUVAJ_NEKRETNINU_PROCEDURE` (IN IdNekretnina int, IN BrPoste varchar(5), IN Adresa varchar(45), IN Vlasnik_JMB varchar(13))
BEGIN
insert into Nekretnina (IdNekretnina,BrPoste,Adresa,Vlasnik_JMB) values (IdNekretnina,BrPoste,Adresa,Vlasnik_JMB);
END$$
DELIMITER ;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
